package javaapplication1;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;

class Student {

    String id;
    String name;
    int age;
    String major;
    double gpa;
    String nickName;

    public Student(String id, String name, int age, String major, double gpa, String nickName) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.major = major;
        this.gpa = gpa;
        this.nickName = nickName;
    }

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public int getAge() {
        return age;
    }

    public String getMajor() {
        return major;
    }

    public double getGpa() {
        return gpa;
    }

    public String getNickName() {
        return nickName;
    }

    public String toString() {
        return id + "," + name + "," + age + "," + major + "," + gpa + "," + nickName;
    }
}

public class NewJFrame extends javax.swing.JFrame {

    // Gobal 
    public static Student[] std;
            
            
            
    
    //int current=0;

    //constructor of NewJFrame Class
    public NewJFrame() {

        initComponents();
        /*
        std[0] = new Student("001","AAA",20,"Arts",3.00,"A");
        std[1] = new Student("002","BBB",21,"Arts",2.80,"B");
        std[2] = new Student("003","CCC",21,"Arts",1.20,"C");
        std[3] = new Student("004","DDD",19,"Arts",2.85,"D");
        std[4] = new Student("005","EEE",20,"Arts",2.65,"E");
        
        for (Student s : std){
            System.out.println(s);
        }
        
        // write file
        try{
            FileWriter fileWriter = new FileWriter("data.txt");
            PrintWriter printWriter = new PrintWriter(fileWriter);
            
            for (Student s : std){
                printWriter.println(s.toString());
            }
            printWriter.close();
            fileWriter.close();
            
        }catch (Exception e){}
         */
        //read

        /*Student[] q = new Student[5]; // save data split(",")
        try{
            FileReader fileReader = new FileReader("data.txt");
            BufferedReader reader = new BufferedReader(fileReader);
            
            for (int i = 0; i < q.length ; i++) {
            /*
                String id = str[0];
                String name = str[1]
                int age = Integer.parseInt(str[2]);
                .
                .
                

         */
            /*
                String[] str = reader.readLine().split(",");
                // "001","AAA",20,"Arts",3.00,"A"  
                // q[i] = new Student(id, name,age,.....);
                q[i] = new Student(str[0],str[1],Integer.parseInt(str[2]),str[3],Double.parseDouble(str[4]),str[5]);
            }
            fileReader.close();
            fileReader.close();

        } catch (Exception e) {}

        // Debug 
        for (Student i : q) {
            System.out.println(i);
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Test Save and Load");

        jButton1.setBackground(new java.awt.Color(255, 204, 255));
        jButton1.setText("load");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("< Prev");

        jButton3.setText("Next >");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton2)
                        .addGap(31, 31, 31)
                        .addComponent(jButton3)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1)
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jButton1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(215, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // show student button
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        std = new Student[5];
        try{
            FileReader fileReader = new FileReader("data.txt");
            BufferedReader reader = new BufferedReader(fileReader);
            
            for (int i = 0; i < std.length ; i++) {
                /*
                String id = str[0];
                String name = str[1]
                int age = Integer.parseInt(str[2]);
                .
                
                .*/
                String[] str = reader.readLine().split(",");
                // q[i] = new Student(id, name,age,.....);
                std[i] = new Student(str[0],str[1],Integer.parseInt(str[2]),str[3],Double.parseDouble(str[4]),str[5]);
            }
            fileReader.close();
            fileReader.close();

        } catch (Exception e) {}
        
        String[] str = std[0].toString().split(",");
        jTextArea1.setText(str[0] + str[1] + str[2] + str[3]+ str[4]+str[5]);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
